import type { DesignTokenDefinition } from "./registry-types.js";

export const legacyAliasTokens = [
  { name: "--bc-page", layer: "legacy", light: "var(--bc-color-canvas)", hostOverridable: false, order: 91 },
  { name: "--bc-surface", layer: "legacy", light: "var(--bc-color-surface)", hostOverridable: false, order: 92 },
  { name: "--bc-raised", layer: "legacy", light: "var(--bc-color-surface-raised)", hostOverridable: false, order: 93 },
  { name: "--bc-hover", layer: "legacy", light: "var(--bc-color-hover)", hostOverridable: false, order: 94 },
  { name: "--bc-selected", layer: "legacy", light: "var(--bc-color-pressed)", hostOverridable: false, order: 95 },
  { name: "--bc-foreground", layer: "legacy", light: "var(--bc-color-text)", hostOverridable: false, order: 96 },
  { name: "--bc-muted", layer: "legacy", light: "var(--bc-color-text-muted)", hostOverridable: false, order: 97 },
  { name: "--bc-faint", layer: "legacy", light: "var(--bc-color-text-faint)", hostOverridable: false, order: 98 },
  { name: "--bc-border", layer: "legacy", light: "transparent", hostOverridable: false, order: 99 },
  { name: "--bc-divider", layer: "legacy", light: "transparent", hostOverridable: false, order: 100 },
  { name: "--bc-input", layer: "legacy", light: "transparent", hostOverridable: false, order: 101 },
  { name: "--bc-control", layer: "legacy", light: "var(--bc-color-control)", hostOverridable: false, order: 102 },
  { name: "--bc-ring", layer: "legacy", light: "var(--bc-color-focus)", hostOverridable: false, order: 103 },
  { name: "--bc-info", layer: "legacy", light: "var(--bc-color-info)", hostOverridable: false, order: 104 },
  { name: "--bc-primary", layer: "legacy", light: "var(--bc-color-primary)", hostOverridable: false, order: 105 },
  { name: "--bc-primary-foreground", layer: "legacy", light: "var(--bc-color-on-primary)", hostOverridable: false, order: 106 },
  { name: "--bc-danger", layer: "legacy", light: "var(--bc-color-danger)", hostOverridable: false, order: 107 },
  { name: "--bc-danger-soft", layer: "legacy", light: "var(--bc-color-danger-soft)", hostOverridable: false, order: 108 },
  { name: "--bc-success", layer: "legacy", light: "var(--bc-color-success)", hostOverridable: false, order: 109 },
  { name: "--bc-warning", layer: "legacy", light: "var(--bc-color-warning)", hostOverridable: false, order: 110 },
  { name: "--bc-color-accent", layer: "legacy", light: "var(--bc-color-focus)", hostOverridable: false, order: 111 },
  { name: "--bc-surface-shadow", layer: "legacy", light: "none", hostOverridable: false, order: 112 },
  { name: "--bc-card-shadow", layer: "legacy", light: "var(--bc-elevation-card)", hostOverridable: false, order: 113 },
  { name: "--bc-elevation-sm", layer: "legacy", light: "var(--bc-elevation-card)", hostOverridable: false, order: 114 },
  { name: "--bc-floating-shadow", layer: "legacy", light: "var(--bc-elevation-float)", hostOverridable: false, order: 115 },
  { name: "--bc-menu-shadow", layer: "legacy", light: "var(--bc-elevation-menu)", hostOverridable: false, order: 116 },
  { name: "--bc-scrim", layer: "legacy", light: "var(--bc-color-scrim)", hostOverridable: false, order: 117 },
] as const satisfies readonly DesignTokenDefinition[];
