import type { DesignTokenDefinition } from "./registry-types.js";

export const foundationTokens = [
  { name: "--bc-font-ui", layer: "foundation", light: 'var(--bc-host-light-font-ui, var(--font-sans, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif))', dark: 'var(--bc-host-dark-font-ui, var(--font-sans, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif))', hostOverridable: true, order: 1 },
  { name: "--bc-text-base", layer: "foundation", light: "var(--font-size-base, var(--font-text-md-size, var(--codex-chat-font-size, 14px)))", hostOverridable: false, order: 2 },
  { name: "--bc-text-md", layer: "foundation", light: "var(--font-size-normal, var(--bc-text-base))", hostOverridable: false, order: 3 },
  { name: "--bc-text-sm", layer: "foundation", light: "var(--font-size-small, max(11px, calc(var(--bc-text-base) - 2px)))", hostOverridable: false, order: 4 },
  { name: "--bc-text-body", layer: "foundation", light: "var(--font-size-tooltip, max(11px, calc(var(--bc-text-base) - 1px)))", hostOverridable: false, order: 5 },
  { name: "--bc-text-caption", layer: "foundation", light: "max(11px, calc(var(--bc-text-base) - 3px))", hostOverridable: false, order: 6 },
  { name: "--bc-text-xs", layer: "foundation", light: "max(10px, calc(var(--bc-text-base) - 4px))", hostOverridable: false, order: 7 },
  { name: "--bc-text-2xs", layer: "foundation", light: "max(9px, calc(var(--bc-text-base) - 5px))", hostOverridable: false, order: 8 },
  { name: "--bc-text-lg", layer: "foundation", light: "calc(var(--bc-text-base) + 1px)", hostOverridable: false, order: 9 },
  { name: "--bc-text-xl", layer: "foundation", light: "calc(var(--bc-text-base) + 5px)", hostOverridable: false, order: 10 },
  { name: "--bc-text-avatar", layer: "foundation", light: "max(8px, calc(var(--bc-text-base) - 6px))", hostOverridable: false, order: 11 },
  { name: "--bc-text-icon", layer: "foundation", light: "calc(var(--bc-text-base) + 2px)", hostOverridable: false, order: 12 },
  { name: "--bc-text-icon-lg", layer: "foundation", light: "calc(var(--bc-text-base) + 3px)", hostOverridable: false, order: 13 },
  { name: "--bc-font-mono", layer: "foundation", light: 'ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace', hostOverridable: false, order: 14 },
  { name: "--bc-control-height", layer: "foundation", light: "calc(var(--bc-text-base) * 2.285714)", hostOverridable: false, order: 15 },
  { name: "--bc-control-padding", layer: "foundation", light: "calc(var(--bc-text-base) * 0.785714)", hostOverridable: false, order: 16 },
  { name: "--bc-row-height", layer: "foundation", light: "calc(var(--bc-text-base) * 2.428571)", hostOverridable: false, order: 17 },
  { name: "--bc-toolbar-height", layer: "foundation", light: "calc(var(--bc-text-base) * 4)", hostOverridable: false, order: 18 },
  { name: "--bc-page-toolbar-height", layer: "foundation", light: "max(50px, calc(var(--bc-control-height) + var(--bc-space-2)))", hostOverridable: false, order: 19 },
  { name: "--bc-completion-notice-bottom", layer: "foundation", light: "var(--bc-space-4)", hostOverridable: false, order: 20 },
  { name: "--bc-agent-inspector-width", layer: "foundation", light: "min(32vw, 516px)", hostOverridable: false, order: 21 },
  { name: "--bc-agent-fullscreen-top", layer: "foundation", light: "0", hostOverridable: false, order: 22 },
  { name: "--bc-agent-fullscreen-left", layer: "foundation", light: "0", hostOverridable: false, order: 23 },
  { name: "--bc-agent-fullscreen-width", layer: "foundation", light: "100vw", hostOverridable: false, order: 24 },
  { name: "--bc-agent-fullscreen-height", layer: "foundation", light: "100dvh", hostOverridable: false, order: 25 },
  { name: "--bc-dialog-fullscreen-top", layer: "foundation", light: "0", hostOverridable: false, order: 26 },
  { name: "--bc-dialog-fullscreen-left", layer: "foundation", light: "0", hostOverridable: false, order: 27 },
  { name: "--bc-dialog-fullscreen-width", layer: "foundation", light: "100vw", hostOverridable: false, order: 28 },
  { name: "--bc-dialog-fullscreen-height", layer: "foundation", light: "100dvh", hostOverridable: false, order: 29 },
  { name: "--bc-mobile-viewport-top", layer: "foundation", light: "0", hostOverridable: false, order: 30 },
  { name: "--bc-mobile-viewport-bottom", layer: "foundation", light: "0px", hostOverridable: false, order: 31 },
  { name: "--bc-mobile-viewport-height", layer: "foundation", light: "100dvh", hostOverridable: false, order: 32 },
  { name: "--bc-icon-sm", layer: "foundation", light: "var(--bc-text-base)", hostOverridable: false, order: 33 },
  { name: "--bc-icon-md", layer: "foundation", light: "calc(var(--bc-text-base) + 2px)", hostOverridable: false, order: 34 },
  { name: "--bc-radius-xs", layer: "foundation", light: "7px", hostOverridable: false, order: 67 },
  { name: "--bc-radius-sm", layer: "foundation", light: "10px", hostOverridable: false, order: 68 },
  { name: "--bc-radius-md", layer: "foundation", light: "13px", hostOverridable: false, order: 69 },
  { name: "--bc-radius-lg", layer: "foundation", light: "16px", hostOverridable: false, order: 70 },
  { name: "--bc-radius-xl", layer: "foundation", light: "20px", hostOverridable: false, order: 71 },
  { name: "--bc-radius-pill", layer: "foundation", light: "999px", hostOverridable: false, order: 72 },
  { name: "--bc-dialog-agent-height", layer: "foundation", light: "400px", hostOverridable: false, order: 73 },
  { name: "--bc-space-1", layer: "foundation", light: "4px", hostOverridable: false, order: 74 },
  { name: "--bc-space-2", layer: "foundation", light: "8px", hostOverridable: false, order: 75 },
  { name: "--bc-space-3", layer: "foundation", light: "12px", hostOverridable: false, order: 76 },
  { name: "--bc-space-4", layer: "foundation", light: "16px", hostOverridable: false, order: 77 },
  { name: "--bc-space-5", layer: "foundation", light: "20px", hostOverridable: false, order: 78 },
  { name: "--bc-space-6", layer: "foundation", light: "24px", hostOverridable: false, order: 79 },
  { name: "--bc-space-7", layer: "foundation", light: "28px", hostOverridable: false, order: 80 },
  { name: "--bc-motion-fast", layer: "foundation", light: "120ms", hostOverridable: false, order: 81 },
  { name: "--bc-motion-normal", layer: "foundation", light: "180ms", hostOverridable: false, order: 82 },
  { name: "--bc-ease-out", layer: "foundation", light: "cubic-bezier(.16, 1, .3, 1)", hostOverridable: false, order: 83 },
  { name: "--bc-focus-ring", layer: "foundation", light: "0 0 0 2px color-mix(in oklch, var(--bc-color-focus) 42%, transparent)", hostOverridable: false, order: 84 },
  { name: "--bc-inset-hairline", layer: "foundation", light: "inset 0 0 0 1px var(--bc-color-hairline)", hostOverridable: false, order: 85 },
  { name: "--bc-elevation-float", layer: "foundation", light: "0 18px 52px rgb(15 15 18 / .16), 0 3px 12px rgb(15 15 18 / .08)", dark: "0 22px 58px rgb(0 0 0 / .5), 0 4px 14px rgb(0 0 0 / .3)", hostOverridable: false, order: 86 },
  { name: "--bc-elevation-menu", layer: "foundation", light: "0 12px 32px rgb(15 15 18 / .13), 0 2px 8px rgb(15 15 18 / .06)", dark: "0 14px 34px rgb(0 0 0 / .38), 0 3px 10px rgb(0 0 0 / .22)", hostOverridable: false, order: 87 },
  { name: "--bc-elevation-card", layer: "foundation", light: "0 1px 2px rgb(15 15 18 / .04), 0 2px 6px rgb(15 15 18 / .05)", dark: "0 1px 2px rgb(0 0 0 / .2), 0 2px 8px rgb(0 0 0 / .22)", hostOverridable: false, order: 88 },
  { name: "--bc-elevation-control", layer: "foundation", light: "0 1px 3px rgb(15 15 18 / .12)", dark: "0 1px 3px rgb(0 0 0 / .22)", hostOverridable: false, order: 89 },
  { name: "--bc-elevation-thumb", layer: "foundation", light: "0 1px 3px rgb(15 15 18 / .16)", dark: "0 1px 3px rgb(0 0 0 / .3)", hostOverridable: false, order: 90 },
  { name: "--bc-leading-tight", layer: "foundation", light: "1", hostOverridable: false, order: 120 },
  { name: "--bc-leading-body", layer: "foundation", light: "1.5", hostOverridable: false, order: 121 },
  { name: "--bc-leading-relaxed", layer: "foundation", light: "1.7", hostOverridable: false, order: 122 },
  { name: "--bc-z-menu", layer: "foundation", light: "120", hostOverridable: false, order: 123 },
] as const satisfies readonly DesignTokenDefinition[];
