function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" }[character] || character));
}

export function deviceAuthorizationPage(id: string, code: string) {
  const authorizationId = escapeHtml(id);
  const userCode = escapeHtml(code);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approve Better Codex Runtime</title><style>body{font-family:system-ui,sans-serif;max-width:30rem;margin:4rem auto;padding:0 1.5rem;color:#202124}main{border:1px solid #ddd;border-radius:12px;padding:2rem}label{display:block;margin-top:1rem}input{box-sizing:border-box;width:100%;padding:.7rem;border:1px solid #bbb;border-radius:6px}button{margin-top:1.25rem;padding:.7rem 1rem;border:0;border-radius:6px;background:#202124;color:#fff;cursor:pointer}output{display:block;margin-top:1rem;color:#b3261e;white-space:pre-wrap}</style></head><body><main><h1>Approve Better Codex Runtime</h1><p>Approve this device for your Hub. The one-time code is <strong>${userCode}</strong>.</p><form id="form"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button>Approve device</button><output id="output"></output></form></main><script>const id=${JSON.stringify(authorizationId)},code=${JSON.stringify(userCode)},form=document.querySelector("#form"),output=document.querySelector("#output");form.addEventListener("submit",async event=>{event.preventDefault();output.textContent="Approving…";const data=new FormData(form);try{let response=await fetch("/web/session",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify({username:data.get("username"),password:data.get("password")})});if(!response.ok)throw new Error("Hub login failed");const session=await response.json();response=await fetch("/api/v1/device-authorizations/"+encodeURIComponent(id)+"/approve",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":session.csrf_token},body:JSON.stringify({user_code:code})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Approval failed");output.style.color="#137333";output.textContent="Device approved. You can return to the CLI.";form.querySelector("button").disabled=true}catch(error){output.textContent=error.message||"Approval failed"}});</script></body></html>`;
}
