import { betterCodexDesignTokensCss } from "./design-system.js";

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" }[character] || character));
}

export function deviceAuthorizationPage(id: string, code: string, sessionPath = "/web/session", hostName = "Hub") {
  const authorizationId = escapeHtml(id);
  const userCode = escapeHtml(code);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approve Better Codex Runtime</title><style>${betterCodexDesignTokensCss()}body{font-family:var(--bc-font-ui);max-width:30rem;margin:4rem auto;padding:0 var(--bc-space-6);color:var(--bc-color-text);background:var(--bc-color-canvas)}main{border-radius:var(--bc-radius-lg);padding:var(--bc-space-7);background:var(--bc-color-surface);box-shadow:var(--bc-elevation-card)}label{display:block;margin-top:var(--bc-space-4)}input{box-sizing:border-box;width:100%;padding:var(--bc-space-3);border:0;border-radius:var(--bc-radius-xs);color:var(--bc-color-text);background:var(--bc-color-input);box-shadow:var(--bc-inset-hairline)}button{margin-top:var(--bc-space-5);padding:var(--bc-space-3) var(--bc-space-4);border:0;border-radius:var(--bc-radius-sm);background:var(--bc-color-primary);color:var(--bc-color-on-primary);cursor:pointer}output{display:block;margin-top:var(--bc-space-4);color:var(--bc-color-danger);white-space:pre-wrap}output[data-tone="success"]{color:var(--bc-color-success)}</style></head><body><main><h1>Approve Better Codex Runtime</h1><p>Approve this device for your ${escapeHtml(hostName)}. The one-time code is <strong>${userCode}</strong>.</p><form id="form"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button>Approve device</button><output id="output"></output></form></main><script>const id=${JSON.stringify(authorizationId)},code=${JSON.stringify(userCode)},sessionPath=${JSON.stringify(sessionPath)},hostName=${JSON.stringify(hostName)},form=document.querySelector("#form"),output=document.querySelector("#output");form.addEventListener("submit",async event=>{event.preventDefault();output.textContent="Approving…";const data=new FormData(form);try{let response=await fetch(sessionPath,{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify({username:data.get("username"),password:data.get("password")})});if(!response.ok)throw new Error(hostName+" login failed");const session=await response.json();response=await fetch("/api/v1/device-authorizations/"+encodeURIComponent(id)+"/approve",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":session.csrf_token},body:JSON.stringify({user_code:code})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Approval failed");output.dataset.tone="success";output.textContent="Device approved. You can return to the CLI.";form.querySelector("button").disabled=true}catch(error){delete output.dataset.tone;output.textContent=error.message||"Approval failed"}});</script></body></html>`;
}
